---
- name: 'Baixa o arquivo de instalação do WordPress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompacta o arquivo de instalação do WordPress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: 'Copia o arquivo de configuração do WordPress'
  copy:
    src: "{{ wp_instalation_dir }}/wp-config-sample.php"
    dest: "{{ wp_instalation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura o wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_instalation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  loop:
    - { regex: 'localhost', value: "{{ wp_db_ip }}" }
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_db_username }}" }
    - { regex: 'password_here', value: "{{ wp_db_password }}" }
  become: yes

- name: 'Configura o Apache para servir o WordPress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - Reinicia o Apache
