---
- name: Apply kube-dash
  command: kubectl apply -f /vagrant/roles/finished/files/kube-dash/deploy.yml

- name: Sleep for 30 seconds and continue with play
  wait_for:
    timeout: 30

- name: Apply kube-dash
  command: kubectl apply -f /vagrant/roles/finished/files/kube-dash/kube-dash.yml

- name: Apply kube-prometheus
  command: "{{ item }}"
  with_items:
    - kubectl apply -f /vagrant/roles/finished/files/kube-prome/manifests/setup
    - kubectl apply -f /vagrant/roles/finished/files/kube-prome/manifests
    - kubectl apply -f /vagrant/roles/finished/files/kube-prome/grafana.yml
    - kubectl apply -f /vagrant/roles/finished/files/kube-prome/prometheus.yml
    - kubectl apply -f /vagrant/roles/finished/files/kube-prome/alertmanager.yml

- name: Apply whoami
  command: kubectl apply -f /vagrant/roles/finished/files/whoami/whoami.yml
