---
- name: 'Instala os pacotes no sistema operacional'
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  loop:
    - mysql-server-5.7
    - python3-pymysql

- name: 'Cria o banco do MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    config_file: "{{ db_config_file }}"
    state: present
  become: yes

- name: 'Cria o usuário do MySQL'
  mysql_user:
    name: "{{ wp_db_username }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    config_file: "{{ db_config_file }}"
    state: present
    host: "{{ item }}"
  loop:
    "{{ wp_host_ip }}"
  become: yes

- name: 'Copia o arquivo mysqld.cnf'
  copy:
    src: /vagrant/roles/mysql/files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  become: yes
  notify:
    - Reinicia o MySQL
