---
- name: Enable kubelet service
  service:
    name: kubelet
    enabled: yes
  become: yes

- name: Pull container images
  command: kubeadm config images pull
  become: yes

- name: Create cluster
  command: "kubeadm init --pod-network-cidr={{ pod_network_cidr }} --apiserver-advertise-address={{ host_ip }}"
  become: yes

- name: Create required directory for vagrant user
  file:
    path: /home/vagrant/.kube
    state: directory
  become: yes

- name: Setup kubeconfig for vagrant user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: 0644
    remote_src: yes
  become: yes

- name: Install network plugin on Master
  command: kubectl apply -f /vagrant/roles/master/files/kube-flannel/deploy.yml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to /vagrant/configs
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: "/vagrant/configs/join-command"

- name: Apply namespace metallb
  command: kubectl apply -f /vagrant/roles/master/files/metallb-system/namespace.yml

- name: Create secret metallb
  shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

- name: Apply load balancer metallb
  command: kubectl apply -f /vagrant/roles/master/files/metallb-system/deploy.yml

- name: Apply config metallb
  command: kubectl apply -f /vagrant/roles/master/files/metallb-system/config.yml

- name: Configure strictARP metallb
  shell: 'kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system'

- name: Apply deploy metrics-server
  command: kubectl apply -f /vagrant/roles/master/files/metrics-server/deploy.yml

- name: Apply deploy ingress-nginx
  command: kubectl apply -f /vagrant/roles/master/files/ingress-nginx/deploy.yml

# - name: Sleep for 60 seconds and continue with play
#   wait_for:
#     timeout: 60
