TIME = Time.now.strftime('%Y%m%d%H%M%S')
CONFIGFILE_HOSTS = "./configs/hosts"

VAGRANT_BOX = "ubuntu/bionic64"

HOSTS = {}
File.readlines(CONFIGFILE_HOSTS).map(&:chomp).each do |line|
    ipaddr, hostname = line.split(/\s+/)
    HOSTS[hostname] = ipaddr
    PRIMARY_SYSTEM = hostname if (line =~ /primary/)
end

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure('2') do |config|
    config.ssh.insert_key = false

    HOSTS.each do |hostname, ipaddr|
        default = if hostname == PRIMARY_SYSTEM then true else false end
        
        config.vm.define hostname, primary: default do |node|
            node.vm.box = VAGRANT_BOX
            node.vm.hostname = hostname
            node.vm.network "public_network", bridge: "wlp2s0", ip: ipaddr, :adapter => 2

            node.vm.provider "virtualbox" do |v|
                v.name = "#{hostname}_#{TIME}"
                v.memory = if default == true then 2048 else 1024 end
                v.cpus = if default == true then 2 else 1 end
            end
            
            node.vm.provision "shell",
                inline: "cp /vagrant/configs/id_rsa.pub /home/vagrant && \
                         chmod 600 /home/vagrant/id_rsa.pub && \
                         chown vagrant:vagrant /home/vagrant/id_rsa.pub"
            
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "provisioning.yml"
                ansible.extra_vars = {
                    host_ip: ipaddr,
                    pod_network_cidr: if default == true then "10.244.0.0/16" else "" end
                }
            end
        end
    end
end
