IMAGE_NAME = "ubuntu/bionic64"

MASTERS_NUM = 1
MASTERS_CPU = 2 
MASTERS_MEM = 2048

WORKERS_NUM = 1
WORKERS_CPU = 1
WORKERS_MEM = 2048

PREFIX_NAME = "k8s"
IP_BASE = "10.10.5."
DNS_HOSTNAME = "#{PREFIX_NAME}-cluster.worksit.com.br"

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..MASTERS_NUM).each do |i|      
        config.vm.define "#{PREFIX_NAME}-m-#{i}" do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "#{IP_BASE}#{i + 10}"
            master.vm.hostname = "#{PREFIX_NAME}-m-#{i}"
            master.vm.provider "virtualbox" do |v|
                v.name = "#{PREFIX_NAME}-m-#{i}"
                v.memory = MASTERS_MEM
                v.cpus = MASTERS_CPU
            end
            master.vm.provision "shell",
                inline: "cp /vagrant/configs/id_rsa.pub /home/vagrant && \
                        chmod 600 /home/vagrant/id_rsa.pub && \
                        chown vagrant:vagrant /home/vagrant/id_rsa.pub"
            master.vm.provision "ansible" do |ansible|
                ansible.playbook = "provisioning.yml"
                ansible.extra_vars = {
                    host_ip: "#{IP_BASE}#{i + 10}",
                    dns_hostname: "#{DNS_HOSTNAME}",
                    pod_network_cidr: "192.168.5.0/16"
                }
            end
        end
    end

    (1..WORKERS_NUM).each do |j|
        config.vm.define "#{PREFIX_NAME}-w-#{j}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "#{IP_BASE}#{j + 10 + MASTERS_NUM}"
            node.vm.hostname = "#{PREFIX_NAME}-w-#{j}"
            node.vm.provider "virtualbox" do |v|
                v.name = "#{PREFIX_NAME}-w-#{j}"
                v.memory = WORKERS_MEM
                v.cpus = WORKERS_CPU
            end
            node.vm.provision "shell",
                inline: "cp /vagrant/configs/id_rsa.pub /home/vagrant && \
                        chmod 600 /home/vagrant/id_rsa.pub && \
                        chown vagrant:vagrant /home/vagrant/id_rsa.pub"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "provisioning.yml"
                ansible.extra_vars = {
                    host_ip: "#{IP_BASE}#{j + 10 + MASTERS_NUM}",
                    dns_hostname: "#{DNS_HOSTNAME}"
                }
            end
        end
    end
end
