TIME = Time.now.strftime('%Y%m%d%H%M%S')
CONFIGFILE_HOSTS = "./configs/hosts"

VAGRANT_BOX = "ubuntu/bionic64"

HOSTS = {}
File.readlines(CONFIGFILE_HOSTS).map(&:chomp).each do |line|
    ipaddr, hostname = line.split(/\s+/)
    HOSTS[hostname] = ipaddr
    PRIMARY_SYSTEM = hostname if (line =~ /primary/)
end

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure('2') do |config|
    config.ssh.insert_key = false

    HOSTS.each do |hostname, ipaddr|
        default = if hostname == PRIMARY_SYSTEM then true else false end
        
        config.vm.define hostname, primary: default do |node|
            node.vm.box = VAGRANT_BOX
            node.vm.hostname = hostname
            node.vm.network "public_network", bridge: "wlp2s0", ip: ipaddr, :adapter => 2

            node.vm.provider "virtualbox" do |v|
                v.name = "#{hostname}_#{TIME}"
                v.memory = if default == true then 4096 else 2048 end
                v.cpus = if default == true then 2 else 1 end
            end

            node.vm.provision "shell",
                inline: "cat /vagrant/configs/id_rsa.pub >> .ssh/authorized_keys"

            if default == true then
                node.vm.provision "shell", inline: <<-EOC
cat <<-'EOF' > /vagrant/hosts
[#{hostname}]
#{ipaddr} host_ip=#{ipaddr} pod_network_cidr=10.244.0.0/16 metallb_addresses=192.168.0.20-192.168.0.30
EOF
    EOC
            else
                node.vm.provision "shell", inline: <<-EOC
cat <<-'EOF' >> /vagrant/hosts
[#{hostname}]
#{ipaddr}
EOF
    EOC
            end
        end
    end

    config.vm.define "ansible" do |ansible|
        ansible.vm.box = VAGRANT_BOX
        ansible.vm.hostname = "ansible"
        #ansible.vm.network "private_network", ip: "10.10.0.1"
        ansible.vm.network "public_network", bridge: "wlp2s0", ip: "192.168.0.9", :adapter => 2

        ansible.vm.provider "virtualbox" do |v|
            v.name = "ansible_#{TIME}"
            v.memory = 1024
            v.cpus = 1
        end

        ansible.vm.provision "shell",
            inline: "cp /vagrant/configs/id_rsa /home/vagrant && \
                     chmod 600 /home/vagrant/id_rsa && \
                     chown vagrant:vagrant /home/vagrant/id_rsa"
    
        ansible.vm.provision "shell",
            inline: "apt-get update && \
                     apt-get install -y software-properties-common && \
                     add-apt-repository --yes --update ppa:ansible/ansible && \
                     apt-get install -y ansible"
    
        ansible.vm.provision "shell",
            inline: "ansible-playbook -i /vagrant/hosts \
                     /vagrant/provisioning-cluster.yml"
        # ansible.vm.provision "shell",
        #     inline: "ansible-playbook -i /vagrant/hosts \
        #              /vagrant/provisioning-finished.yml"
    end
end
