---
- hosts: all
  handlers:
    - name: Reinicia o Apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Atualiza o cache do repositório de pacote apt'
      apt:
        update_cache: yes
      become: yes

    - name: 'Instala os pacotes no sistema operacional'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      loop:
        - php7.2
        - apache2
        - libapache2-mod-php7.2
        - php7.2-gd
        - libssh2-1
        - mysql-server-5.7
        - php7.2-mysql
        - python3-pymysql

    - name: 'Cria o banco do MySQL'
      mysql_db:
        name: wordpress_db
        config_file: /etc/mysql/debian.cnf
        state: present
      become: yes

    - name: 'Cria o usuário do MySQL'
      mysql_user:
        name: wordpress_user
        password: '12345'
        priv: 'wordpress_db.*:ALL'
        config_file: /etc/mysql/debian.cnf
        state: present
      become: yes

    - name: 'Baixa o arquivo de instalação do WordPress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: 'Descompacta o arquivo de instalação do WordPress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes

    - name: 'Copia o arquivo de configuração do WordPress'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configura o wp-config com as entradas do banco de dados'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      loop:
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'username_here', value: 'wordpress_user' }
        - { regex: 'password_here', value: '12345' }
      become: yes

    - name: 'Configura o Apache para servir o WordPress'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - Reinicia o Apache
