apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
      volumeID: vol-0a01d3aba9f01139a
      fsType: ext4
  storageClassName: ebs-sc
